### ISSUE TITLE
Is this fork also defunct?

### ISSUE THREAD

**Issue by jaredmoody** [spencerking/mastodon.cr#2]
Or do you have interest in updating it for Crystal 0.35? I'm willing to help...

**Comment by spencerking** [comment]
I'll look into it later this evening and let you know.

**Comment by spencerking** [comment]
I've got a small streaming client that uses this library and it seems to be working fine now on 0.35.1. Let me know if you run into any further issues.

**Comment by jaredmoody** [comment]
The specs definitely don't pass on 0.35.1 - I think mostly because `spec2` is defunct. 

What do you think about setting up a CI so that it can automatically test different versions of crystal? Lots of free CI services for OSS.

**Comment by jaredmoody** [comment]
I've updated `client_spec.cr` to use the built in spec library and have it passing - I'll update the others and send a PR when all specs are passing.

**Comment by spencerking** [comment]
Honestly, I was not aware of spec. The spec2 results don't seem _that_ tough to resolve, but I'll wait for your PR with the complete fix. 

I'll look into free CI services, Travis seems to be preferred.
